version: '3.1'

# docker container run --name test -p 80:80 -v $(pwd):/src burakalp/test
#pwd yerine nokta var volume de : sol tarafıdr

services:
  test:
    image: burakalp/test
    volumes:
      - .:/src
    ports:
      - '80:80'
